# Generated by Django 5.1.5 on 2025-02-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('Retiro en Local', 'Retiro en Local'), ('Retiro en 526 y 133', 'Retiro en 526 y 133'), ('Envío dentro de La Plata', 'Envío dentro de La Plata (+$8.000)'), ('Envío fuera de La Plata', 'Envío fuera de La Plata (+$15.000)')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('Cuenta DNI', 'Cuenta DNI'), ('Banco Nación', 'Banco Nación'), ('Efectivo en Local', 'Efectivo en Local')], max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='productos.itemcarrito')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Cuenta DNI', 'Cuenta DNI'), ('Banco Nación', 'Banco Nación'), ('Efectivo en Local', 'Efectivo en Local')], max_length=25)),
                ('metodo_entrega', models.CharField(choices=[('Retiro en Local', 'Retiro en Local'), ('Retiro en 526 y 133', 'Retiro en 526 y 133'), ('Envío dentro de La Plata', 'Envío dentro de La Plata (+$8.000)'), ('Envío fuera de La Plata', 'Envío fuera de La Plata (+$15.000)')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('productos', models.ManyToManyField(to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
