# Generated by Django 5.1.5 on 2025-02-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ropa_hombre', 'Ropa de Hombre'), ('ropa_mujer', 'Ropa de Mujer'), ('ropa_ninos', 'Ropa de Niños')], default='ropa_hombre', max_length=50),
        ),
    ]
