# Generated by Django 5.1.5 on 2025-02-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('rojo', 'Rojo'), ('naranja', 'Naranja'), ('amarillo', 'Amarillo'), ('verde', 'Verde'), ('celeste', 'Celeste'), ('azul', 'Azul'), ('violeta', 'Violeta'), ('rosa', 'Rosa'), ('negro', 'Negro'), ('blanco', 'Blanco'), ('gris', 'Gris'), ('marrón', 'Marrón')], default='rojo', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
